  services:
    db:
      image: postgres
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: example
      volumes: 
        - ./postgres_data:/data

    redis:
      image: redis
      command: ['redis-server', '--appendonly', 'yes']
      ports:
        - 6379:6379
      volumes:
      - ./redis_data:/data
