services:
  app:
    image: frontend-prod
    build:
      context: ./frontend/. 
      dockerfile: Dockerfile 
    container_name: project-front-prod  
  server:
    image: backend-prod
    build:
      context: ./backend/. 
      dockerfile: Dockerfile 
    # ports:
    #   - 3003:3003
    container_name: project-back-prod
    environment: 
      - REDIS_URL=redis://redis:6379
      - DATABASE=postgres://postgres:example@db:5432/postgres
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-nginx
    depends_on:
      - app 
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes: 
      - ./postgres_data:/data
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - 6379:6379
    volumes:
    - ./redis_data:/data