services:
  - type: web
    env: node
    name: project-prod-backend
    repo: https://github.com/Samapa1/FullstackProject
    buildCommand: cd backend; npm install 
    startCommdand: cd backend; npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: project-prod-db 
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: project-prod-redis 
          property: connectionString

  - type: web
    env: static
    name: project-prod-frontend
    repo: https://github.com/Samapa1/FullstackProject
    buildCommand: cd frontend; npm build
    staticPublisPath: ./frontend/dist/assets

  - type: redis
    name: project-prod-redis 
    ipAllowList: []

databases: 
  - name: project-prod-db





  



