services:
  - type: web
    env: node
    name: project-prod-backend
    repo: https://github.com/Samapa1/FullstackProject
    buildCommand: cd backend; npm ci 
    startCommand: cd backend; npm start
    plan: free
    envVars:
      - key: DATABASE
        fromDatabase:
          name: project-prod-db 
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: project-prod-redis 
          property: connectionString

  - type: web
    env: static
    name: project-prod-frontend
    repo: https://github.com/Samapa1/FullstackProject
    buildCommand: cd frontend; npm ci; npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://project-prod-backend.onrender.com/api/

  - type: redis
    name: project-prod-redis 
    ipAllowList: []
    plan: free

databases: 
  - name: project-prod-db
    plan: free







  



