services:
- type: web
    runtime: image
    name: project-front-prod
    image:
      url: docker.io/saijapa/bookapp-frontend:latest
- type: web
    runtime: image
    name: project-back-prod
    image:
      url: docker.io/saijapa/bookapp-backend:latest
- type: web 
    runtime: image
    name: app-nginx
    image:
      url: docker.io/library/nginx:latest
    envVars:
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: 8080
- type: web 
    runtime: image
    name: app-postgres
    image:
      url: docker.io/library/postgres:latest
    envVars:
      - key: REDIS_URL
        value: redis://redis:6379
      - key: DATABASE
        value: postgres://postgres:example@db:5432/postgres
      - key: PORT
        value: 5432
- type: web 
    runtime: image
    name: app-redis
    image:
      url: docker.io/library/redis:latest
    envVars:
      - key: PORT
        value: 6379


  



