POST http://localhost:3003/api/books
Content-Type: application/json
Authorization: Bearer xxx

{
    "author": "S.T Davids",
    "title": "Tales of the Reindeer 5",
    "year": 2017,
    "numberOfBooks": 3
}
