POST http://localhost:3003/api/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhhbm51aCIsImlkIjoxLCJpYXQiOjE3MjgzOTU5Nzl9.NFOoC4v33ps2hdUGnDNg-v2CyxCKeF8LYG0xSAG6JjY

{
    "author": "J.K.Rowling",
    "title": "Harry Potter and the Philosopher's Stone",
    "year": 1997,
    "number_of_books": 2
}
