POST http://localhost:3003/api/books
Content-Type: application/json
Authorization: xxx

{
    "author": "J.K.Rowling",
    "title": "Harry Potter and the Philosopher's Stone 2",
    "year": 1997,
    "number_of_books": 2
}
