POST http://localhost:3003/api/users/2
Content-Type: application/json
Authorization: Bearer xxx

{
    "name": "Ulla Lahtelainen",
    "email": "ulla.lahtelainenn@gmail.com",
    "oldPassword": "",
    "newPassword": ""
}
